# Generated by Django 5.1 on 2024-08-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh', models.CharField(max_length=64)),
                ('mm', models.CharField(max_length=64)),
            ],
        ),
    ]
