# Generated by Django 5.1 on 2024-08-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='zh',
            new_name='mz',
        ),
    ]
