# Generated by Django 5.1 on 2024-08-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpy', '0002_rename_zh_userinfo_mz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='zh',
        ),
    ]
